WebEstoque/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebEstoque.Models
{
    [Table("Cliente")]
    public class Cliente : Usuario
    {
        [Required, Column(TypeName = "char(14)")]
        public string CPF { get; set; }

        public DateTime DataNascimento { get; set; }

        [NotMapped]
        public int Idade
        {
            get => (int)Math.Floor((DateTime.Now - DataNascimento).TotalDays / 365.2425);            
        }

        public ICollection<Endereco>? Enderecos { get; set; }

        public ICollection<Pedido>? Pedidos { get; set; }
    }
}

WebEstoque/Controllers/ClienteController.cs
using System.Linq;
using System.Threading.Tasks;
using WebEstoque.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebEstoque.Infrastructure;

namespace WebEstoque.Controllers
{
    public class ClienteController : Controller
    {
        private readonly DataContext _context;

        public ClienteController(DataContext context)
        {
            this._context = context;
        }

        public async Task<IActionResult> Index()
        {
            var clientes = await _context.Clientes.OrderBy(x => x.Nome).AsNoTracking().ToListAsync();
            return View(clientes);
        }

        [HttpGet]
        public async Task<IActionResult> Cadastrar(int? id)
        {
            if (id.HasValue)
            {
                var cliente = await _context.Clientes.FindAsync(id);
                if (cliente == null)
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado.", TipoMensagem.Erro);
                    return RedirectToAction("Index");
                }
                return View(cliente);
            }
            return View(new Cliente());
        }

        private bool ClienteExiste(int id)
        {
            return _context.Clientes.Any(x => x.IdUsuario == id);
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(int? id, [FromForm] Cliente cliente)
            {
            if (ModelState.IsValid)
            {
                if (id.HasValue)
                {
                    if (ClienteExiste(id.Value))
                    {
                        _context.Clientes.Update(cliente);
                        _context.Entry(cliente).Property(x => x.Senha).IsModified = false;
                        if (await _context.SaveChangesAsync() > 0)
                        {
                            TempData["mensagem"] = MensagemModel.Serializar("Cliente alterado com sucesso.");
                        }
                        else
                        {
                            TempData["mensagem"] = MensagemModel.Serializar("Erro ao alterar cliente.", TipoMensagem.Erro);
                        }
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado.", TipoMensagem.Erro);
                    }
                }
                else
                {
                    _context.Clientes.Add(cliente);
                    if (await _context.SaveChangesAsync() > 0)
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Cliente cadastrado com sucesso.");
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Erro ao cadastrar cliente.", TipoMensagem.Erro);
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(cliente);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Excluir(int? id)
        {
            if (!id.HasValue)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não informado.", TipoMensagem.Erro);
                return RedirectToAction(nameof(Index));
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado.", TipoMensagem.Erro);
                return RedirectToAction(nameof(Index));
            }

            return View(cliente);
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
                if (await _context.SaveChangesAsync() > 0)
                    TempData["mensagem"] = MensagemModel.Serializar("Cliente excluído com sucesso.");
                else
                    TempData["mensagem"] = MensagemModel.Serializar("Não foi possível excluir o cliente.", TipoMensagem.Erro);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado.", TipoMensagem.Erro);
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

WebEstoque/Controllers/PedidoController.cs
using WebEstoque.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebEstoque.Infrastructure;

namespace WebEstoque.Controllers
{
    public class PedidoController : Controller
    {
        private readonly DataContext _context;

        public PedidoController(DataContext context)
        {
            this._context = context;
        }

        public async Task<IActionResult> Index(int? cid)
        {
            if (cid.HasValue)
            {
                var cliente = await _context.Clientes.FindAsync(cid);
                if (cliente != null)
                {
                    var pedidos = await _context.Pedidos
                        .Where(p => p.IdCliente == cid)
                        .OrderByDescending(x => x.IdPedido)
                        .AsNoTracking().ToListAsync();

                    ViewBag.Cliente = cliente;
                    return View(pedidos);
                }
                else
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado",
                        TipoMensagem.Erro);
                    return RedirectToAction("Index", "Cliente");
                }
            }
            else
            {
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não informado",
                    TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Cadastrar(int? cid)
        {
            if (cid.HasValue)
            {
                var cliente = await _context.Clientes.FindAsync(cid);
                if (cliente != null)
                {
                    _context.Entry(cliente).Collection(c => c.Pedidos).Load();
                    Pedido pedido = null;
                    if (_context.Pedidos.Any(p => p.IdCliente == cid && !p.DataPedido.HasValue))
                    {
                        pedido = await _context.Pedidos
                            .FirstOrDefaultAsync(p => p.IdCliente == cid && !p.DataPedido.HasValue);
                    }
                    else
                    {
                        pedido = new Pedido { IdCliente = cid.Value, ValorTotal = 0 };
                        cliente.Pedidos.Add(pedido);
                        await _context.SaveChangesAsync();
                    }
                    return RedirectToAction("Index", "ItemPedido", new { ped = pedido.IdPedido });
                }
                TempData["mensagem"] = MensagemModel.Serializar("Cliente não encontrado", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Cliente não informado", TipoMensagem.Erro);
            return RedirectToAction("Index", "Cliente");
        }

        private bool PedidoExiste(int id)
        {
            return _context.Pedidos.Any(x => x.IdPedido == id);
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(int? id, [FromForm] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                if (id.HasValue)
                {
                    if (PedidoExiste(id.Value))
                    {
                        _context.Pedidos.Update(pedido);
                        if (await _context.SaveChangesAsync() > 0)
                        {
                            TempData["mensagem"] = MensagemModel.Serializar("Pedido alterada com sucesso.");
                        }
                        else
                        {
                            TempData["mensagem"] = MensagemModel.Serializar("Erro ao alterar pedido.", TipoMensagem.Erro);
                        }
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrada.", TipoMensagem.Erro);
                    }
                }
                else
                {
                    _context.Pedidos.Add(pedido);
                    if (await _context.SaveChangesAsync() > 0)
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Pedido cadastrada com sucesso.");
                    }
                    else
                    {
                        TempData["mensagem"] = MensagemModel.Serializar("Erro ao cadastrar pedido.", TipoMensagem.Erro);
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(pedido);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Excluir(int? id)
        {
            if (!id.HasValue)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não informado.", TipoMensagem.Erro);
                return RedirectToAction("Index");
            }

            if (!PedidoExiste(id.Value))
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }

            var pedido = await _context.Pedidos
                .Include(p => p.Cliente)
                .Include(p => p.ItensPedido)
                .ThenInclude(i => i.Produto)
                .FirstOrDefaultAsync(p => p.IdPedido == id);

            return View(pedido);
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int id)
        {
            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido != null)
            {
                _context.Pedidos.Remove(pedido);
                if (await _context.SaveChangesAsync() > 0)
                    TempData["mensagem"] = MensagemModel.Serializar("Pedido excluído com sucesso.");
                else
                    TempData["mensagem"] = MensagemModel.Serializar("Não foi possível excluir o pedido.", TipoMensagem.Erro);
                return RedirectToAction(nameof(Index), new { cid = pedido.IdCliente });
            }
            else
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction(nameof(Index), "Cliente");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Fechar(int? id)
        {
            if (!id.HasValue)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não informado.", TipoMensagem.Erro);
                return RedirectToAction("Index");
            }

            if (!PedidoExiste(id.Value))
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }

            var pedido = await _context.Pedidos
                .Include(p => p.Cliente)
                .Include(p => p.ItensPedido)
                .ThenInclude(i => i.Produto)
                .FirstOrDefaultAsync(p => p.IdPedido == id);

            return View(pedido);
        }

        [HttpPost]
        public async Task<IActionResult> Fechar(int id)
        {
            if (PedidoExiste(id))
            {
                var pedido = await _context.Pedidos
                    .Include(p => p.Cliente)
                    .Include(p => p.ItensPedido)
                    .ThenInclude(i => i.Produto)
                    .FirstOrDefaultAsync(p => p.IdPedido == id);

                if (pedido.ItensPedido.Count() > 0)
                {
                    pedido.DataPedido = DateTime.Now;
                    foreach (var item in pedido.ItensPedido)
                        item.Produto.Estoque -= item.Quantidade;
                    if (await _context.SaveChangesAsync() > 0)
                        TempData["mensagem"] = MensagemModel.Serializar("Pedido fechado com sucesso.");
                    else
                        TempData["mensagem"] = MensagemModel.Serializar("Não foi possível fechar o pedido.", TipoMensagem.Erro);
                    return RedirectToAction("Index", new { cid = pedido.IdCliente });
                }
                else
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Não é possível fechar um pedido sem itens.", TipoMensagem.Erro);
                    return RedirectToAction("Index", new { cid = pedido.IdCliente });
                }
            }
            else
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Entregar(int? id)
        {
            if (!id.HasValue)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não informado.", TipoMensagem.Erro);
                return RedirectToAction("Index");
            }

            if (!PedidoExiste(id.Value))
            {
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }

            var pedido = await _context.Pedidos
                .Include(p => p.Cliente)
                .ThenInclude(c => c.Enderecos)
                .Include(p => p.ItensPedido)
                .ThenInclude(i => i.Produto)
                .FirstOrDefaultAsync(p => p.IdPedido == id);

            return View(pedido);
        }

        [HttpPost]
        public async Task<IActionResult> Entregar(int idPedido, int idEndereco)
        {
            if (PedidoExiste(idPedido))
            {
                var pedido = await _context.Pedidos
                    .Include(p => p.Cliente)

WebEstoque/Views/Cliente/Cadastrar.cshtml
@model Cliente
@{
    if (Context.Request.RouteValues.ContainsKey("id"))
        ViewBag.Subtitulo = "Alteração de Cliente";
    else
        ViewBag.Subtitulo = "Cadastro de Cliente";
}

<h1 class="text-primary">@ViewBag.Subtitulo</h1>
<hr>

<form asp-action="Cadastrar" class="row">
    <input type="hidden" asp-for="@Model.IdUsuario">
    <div class="form-group col-sm-8 col-lg-4">
        <label asp-for="@Model.Nome">Nome:</label><br>
        <input asp-for="@Model.Nome" class="form-control" autofocus>
        <span asp-validation-for="@Model.Nome" class="text-danger"></span>
    </div>
    <div class="w-100"></div>
    <div class="form-group col-sm-8 col-lg-4">
        <label asp-for="@Model.CPF">CPF:</label><br>
        <input asp-for="@Model.CPF" class="form-control">
        <span asp-validation-for="@Model.CPF" class="text-danger"></span>
    </div>
    <div class="w-100"></div>
    <div class="form-group col-sm-8 col-lg-4">
        <label asp-for="@Model.DataNascimento">Data Nascimento:</label><br>
        <input asp-for="@Model.DataNascimento" class="form-control" type="date">
        <span asp-validation-for="@Model.DataNascimento" class="text-danger"></span>
    </div>
    <div class="w-100"></div>
    <div class="form-group col-sm-8 col-lg-4">
        <label asp-for="@Model.Email">E-mail:</label><br>
        <input asp-for="@Model.Email" class="form-control" type="email">
        <span asp-validation-for="@Model.Email" class="text-danger"></span>
    </div>
    @if (!Context.Request.RouteValues.ContainsKey("id"))
    {
        <div class="w-100"></div>
        <div class="form-group col-sm-8 col-lg-4">
            <label asp-for="@Model.Senha">Senha:</label><br>
            <input asp-for="@Model.Senha" class="form-control" type="password">
            <span asp-validation-for="@Model.Senha" class="text-danger"></span>
        </div>
    }
    <div class="mt-3">
        <a asp-action="Index" class="btn btn-outline-secondary">Cancelar</a>
        <button class="btn btn-primary" type="submit">Salvar</button>
    </div>
</form>

WebEstoque/Views/Cliente/Excluir.cshtml
@model Cliente
@{
    ViewBag.Subtitulo = "Exclusão de Cliente";
}

<h1 class="text-primary">@ViewBag.Subtitulo</h1>
<hr>
<h4>Deseja realmente excluir o cliente <span class="text-danger">@Model.Nome?</span></h4>

<form asp-action="Excluir" class="w-25">
    <input type="hidden" asp-for="@Model.IdUsuario">
    <div class="mt-3">
        <a asp-action="Index" class="btn btn-success">Não</a>
        <button class="btn btn-danger" type="submit">Sim</button>
    </div>
</form>

WebEstoque/Views/Cliente/Index.cshtml
@model IEnumerable<Cliente>

@{
    ViewData["Title"] = "Client Page";
    ViewBag.Subtitulo = "Clientes";
}


<header class="d-flex justify-content-between align-items-center">
    <div>
        <h1 class="text-primary"> @ViewBag.Subtitulo</h1>
    </div>
    <div>
        <a asp-action="Cadastrar" class="btn btn-primary">Novo Cliente</a>
    </div>
</header>
<hr>


<partial name="~/views/shared/partialview/_Mensagem.cshtml" />

@if (Model.Count() > 0)
{
    <table class="table table-striped tabela-clientes">
        <thead>
            <tr>
                <th>Nome</th>
                <th>E-mail</th>
                <th>CPF</th>
                <th>Idade</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cliente in Model)
            {
                <tr>
                    <td>@cliente.Nome</td>
                    <td>@cliente.Email</td>
                    <td>@cliente.CPF</td>
                    <td>@cliente.Idade</td>
                    <td>
                        <a asp-action="Index" asp-controller="Pedido" asp-route-cid="@cliente.IdUsuario" class="btn btn-sm btn-info"><i class="bi-cart" title="Pedidos"></i></a>
                        <a asp-action="Index" asp-controller="Endereco" asp-route-cid="@cliente.IdUsuario" class="btn btn-sm btn-success"><i class="bi-mailbox" title="Endereços"></i></a>
                        <a asp-action="Cadastrar" asp-route-id="@cliente.IdUsuario" class="btn btn-sm btn-secondary"><i class="bi-pencil" title="Alterar cliente"></i></a>
                        <a asp-action="Excluir" asp-route-id="@cliente.IdUsuario" class="btn btn-sm btn-danger"><i class="bi-trash" title="Excluir cliente"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não há nenhum cliente cadastrado.</p>
}