WebEstoque/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebEstoque.Models
{
    [Table("Pedido")]
    public class Pedido
    {
        [Key]
        public int IdPedido { get; set; }

        public DateTime? DataPedido { get; set; }

        public DateTime? DataEntrega { get; set; }

        public double? ValorTotal { get; set; }

        public int IdCliente { get; set; }

        [ForeignKey("IdCliente")]
        public Cliente? Cliente { get; set; }

        public Endereco? EnderecoEntrega { get; set; }

        public ICollection<ItemPedido>? ItensPedido { get; set; }
    }
}

WebEstoque/Controllers/ItemPedidoController.cs
using WebEstoque.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebEstoque.Infrastructure;

namespace WebEstoque.Controllers
{
    public class ItemPedidoController : Controller
    {
        private readonly DataContext _context;

        public ItemPedidoController(DataContext context)
        {
            this._context = context;
        }

        public async Task<IActionResult> Index(int? ped)
        {
            if (ped.HasValue)
            {
                if (_context.Pedidos.Any(p => p.IdPedido == ped))
                {
                    var pedido = await _context.Pedidos
                        .Include(p => p.Cliente)
                        .Include(p => p.ItensPedido.OrderBy(i => i.Produto.Nome))
                        .ThenInclude(i => i.Produto)
                        .FirstOrDefaultAsync(p => p.IdPedido == ped);

                    ViewBag.Pedido = pedido;
                    return View(pedido.ItensPedido);
                }
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Pedido não informado.", TipoMensagem.Erro);
            return RedirectToAction("Index", "Cliente");
        }

        [HttpGet]
        public async Task<IActionResult> Cadastrar(int? ped, int? prod)
        {
            if (ped.HasValue)
            {
                if (_context.Pedidos.Any(p => p.IdPedido == ped))
                {
                    var produtos = _context.Produtos
                        .OrderBy(x => x.Nome)
                        .Select(p => new { p.IdProduto, NomePreco = $"{p.Nome} ({p.Preco:C})" })
                        .AsNoTracking().ToList();
                    var produtosSelectList = new SelectList(produtos, "IdProduto", "NomePreco");
                    ViewBag.Produtos = produtosSelectList;

                    if (prod.HasValue && ItemPedidoExiste(ped.Value, prod.Value))
                    {
                        var itemPedido = await _context.ItensPedidos
                            .Include(i => i.Produto)
                            .FirstOrDefaultAsync(i => i.IdPedido == ped && i.IdProduto == prod);
                        return View(itemPedido);
                    }
                    else
                    {
                        return View(new ItemPedido()
                        { IdPedido = ped.Value, ValorUnitario = 0, Quantidade = 1 });
                    }
                }
                TempData["mensagem"] = MensagemModel.Serializar("Pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }
            TempData["mensagem"] = MensagemModel.Serializar("Pedido não informado.", TipoMensagem.Erro);
            return RedirectToAction("Index", "Cliente");
        }

        private bool ItemPedidoExiste(int ped, int prod)
        {
            var result = _context.ItensPedidos.Any(x => x.IdPedido == ped && x.IdProduto == prod);
            return result;
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar([FromForm] ItemPedido itemPedido)
        {
            if (ModelState.IsValid)
            {
                if (itemPedido.IdPedido > 0)
                {
                    var produto = await _context.Produtos.FindAsync(itemPedido.IdProduto);
                    itemPedido.ValorUnitario = (double)produto.Preco;
                    if (ItemPedidoExiste(itemPedido.IdPedido, itemPedido.IdProduto))
                    {
                        _context.ItensPedidos.Update(itemPedido);
                        if (await _context.SaveChangesAsync() > 0)
                            TempData["mensagem"] = MensagemModel.Serializar("Item de pedido alterado com sucesso.");
                        else
                            TempData["mensagem"] = MensagemModel.Serializar("Erro ao alterar item de pedido.", TipoMensagem.Erro);
                    }
                    else
                    {
                        _context.ItensPedidos.Add(itemPedido);
                        if (await _context.SaveChangesAsync() > 0)
                            TempData["mensagem"] = MensagemModel.Serializar("Item de pedido cadastrado com sucesso.");
                        else
                            TempData["mensagem"] = MensagemModel.Serializar("Erro ao cadastrar item de pedido.", TipoMensagem.Erro);
                    }
                    var pedido = await _context.Pedidos.FindAsync(itemPedido.IdPedido);
                    pedido.ValorTotal = _context.ItensPedidos
                        .Where(i => i.IdPedido == itemPedido.IdPedido)
                        .Sum(i => i.ValorUnitario * i.Quantidade);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", new { ped = itemPedido.IdPedido });
                }
                else
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Pedido não informado.", TipoMensagem.Erro);
                    return RedirectToAction("Index", "Cliente");
                }
            }
            else
            {
                var produtos = _context.Produtos
                        .OrderBy(x => x.Nome)
                        .Select(p => new { p.IdProduto, NomePreco = $"{p.Nome} ({p.Preco:C})" })
                        .AsNoTracking().ToList();
                var produtosSelectList = new SelectList(produtos, "IdProduto", "NomePreco");
                ViewBag.Produtos = produtosSelectList;

                return View(itemPedido);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Excluir(int? ped, int? prod)
        {
            if (!ped.HasValue || !prod.HasValue)
            {
                TempData["mensagem"] = MensagemModel.Serializar("Item de pedido não informado.", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }

            if (!ItemPedidoExiste(ped.Value, prod.Value))
            {
                TempData["mensagem"] = MensagemModel.Serializar("Item de pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction("Index", "Cliente");
            }

            var itemPedido = await _context.ItensPedidos.FindAsync(ped, prod);
            _context.Entry(itemPedido).Reference(i => i.Produto).Load();
            return View(itemPedido);
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int idPedido, int idProduto)
        {
            var itemPedido = await _context.ItensPedidos.FindAsync(idPedido, idProduto);
            if (itemPedido != null)
            {
                _context.ItensPedidos.Remove(itemPedido);
                if (await _context.SaveChangesAsync() > 0)
                {
                    TempData["mensagem"] = MensagemModel.Serializar("Item de pedido excluído com sucesso.");
                    var pedido = await _context.Pedidos.FindAsync(itemPedido.IdPedido);
                    pedido.ValorTotal = _context.ItensPedidos
                        .Where(i => i.IdPedido == itemPedido.IdPedido)
                        .Sum(i => i.ValorUnitario * i.Quantidade);
                    await _context.SaveChangesAsync();
                }
                else
                    TempData["mensagem"] = MensagemModel.Serializar("Não foi possível excluir o item de pedido.", TipoMensagem.Erro);
                return RedirectToAction("Index", new { ped = idPedido });
            }
            else
            {
                TempData["mensagem"] = MensagemModel.Serializar("Item de pedido não encontrado.", TipoMensagem.Erro);
                return RedirectToAction("Index", new { ped = idPedido });
            }
        }
    }
}

WebEstoque/Views/Pedido/Entregar.cshtml
@model Pedido
@using WebEstoque.Models
@{
    ViewBag.Subtitulo = $"Registro de Entrega do Pedido <b>{Model.IdPedido:D4}</b>";
}

<h1 class="text-primary">@Html.Raw(ViewBag.Subtitulo)</h1>
<hr>
<h6>Cliente: <b class="text-dark">@Model.Cliente.Nome</b></h6>
<hr>
@if (Model.ItensPedido.Count > 0)
{
    <h6><b>Itens do pedido:</b></h6>
    <hr>
    @foreach (var item in Model.ItensPedido)
    {
        <h6>@item.Produto.Nome (@item.Quantidade x @item.ValorUnitario.ToString("C") = @item.ValorItem.ToString("C")</h6>
    }
    <hr>
    <h6><b>Valor Total do Pedido: @Model.ValorTotal.Value.ToString("C")</b></h6>
}
else
{
    <h6><b>Não há itens no pedido.</b></h6>
}

@if (Model.Cliente.Enderecos.Count() > 0)
{
    <h3>Escolha o endereço de entrega:</h3>
    <form asp-action="Entregar">
        <input type="hidden" asp-for="@Model.IdPedido">
        <div class="mt-3">
            @foreach (var endereco in Model.Cliente.Enderecos)
            {
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="IdEndereco" value="@endereco.IdEndereco" checked="@endereco.Selecionado"
                id='@($"opcao{endereco.IdEndereco}")'>
                    <label class="form-check-label" for='@($"opcao{endereco.IdEndereco}")'>
                        @endereco.EnderecoCompleto
                    </label>
                </div>
            }
            <hr>
            <a asp-action="Index" asp-route-cid="@Model.IdCliente" class="btn btn-secondary">Cancelar</a>
            <button class="btn btn-success" type="submit">Registrar Entrega</button>
        </div>
    </form>
}
else
{
    <h6>Este cliente ainda não possui endereço cadastrado.</h6>
}

WebEstoque/Views/Pedido/Excluir.cshtml
@model Pedido
@using WebEstoque.Models
@{
    ViewBag.Subtitulo = $"Exclusão do Pedido <b>{Model.IdPedido:D4}</b>";
}

<h1 class="text-primary">@Html.Raw(ViewBag.Subtitulo)</h1>
<hr>
<h6>Cliente: <b class="text-dark">@Model.Cliente.Nome</b></h6>
@if (Model.DataEntrega.HasValue)
{
    <h6>Endereço de entrega: @Model.EnderecoEntrega.EnderecoCompleto</h6>
}
<hr>
@if (Model.ItensPedido.Count > 0)
{
    <h6><b>Itens do pedido:</b></h6>
    <hr>
    @foreach (var item in Model.ItensPedido)
    {   
        <h6>@item.Produto.Nome (@item.Quantidade x @item.ValorUnitario.ToString("C") = @item.ValorItem.ToString("C")</h6>
    }
    <hr>
    <h6><b>Valor Total do Pedido: @Model.ValorTotal.Value.ToString("C")</b></h6>    
}
else
{
    <h6><b>Não há itens no pedido.</b></h6>
}

<h4>Deseja realmente excluir esse pedido?</h4>

<form asp-action="Excluir" class="w-25">
    <input type="hidden" asp-for="@Model.IdPedido">
    <div class="mt-3">
        <a asp-action="Index" asp-route-cid="@Model.IdCliente" class="btn btn-success">Não</a>
        <button class="btn btn-danger" type="submit">Sim</button>
    </div>
</form>

WebEstoque/Views/Pedido/Fechar.cshtml
@model Pedido
@using WebEstoque.Models
@{
    ViewBag.Subtitulo = $"Fechamento do Pedido <b>{Model.IdPedido:D4}</b>";
}

<h1 class="text-primary">@Html.Raw(ViewBag.Subtitulo)</h1>
<hr>
<h6>Cliente: <b class="text-dark">@Model.Cliente.Nome</b></h6>
@if (Model.DataEntrega.HasValue)
{
    <h6>Endereço de entrega: @Model.EnderecoEntrega.EnderecoCompleto</h6>
}
<hr>
@if (Model.ItensPedido.Count > 0)
{
    <h6><b>Itens do pedido:</b></h6>
    <hr>
    @foreach (var item in Model.ItensPedido)
    {
        <h6>@item.Produto.Nome - @item.Quantidade x @item.ValorUnitario.ToString("C") = @item.ValorItem.ToString("C")</h6>
    }
    <hr>
    <h6><b>Valor Total do Pedido: @Model.ValorTotal.Value.ToString("C")</b></h6>
}
else
{
    <h6><b>Não há itens no pedido.</b></h6>
}

<h4>Deseja realmente fechar esse pedido?</h4>

<form asp-action="Fechar" class="w-25">
    <input type="hidden" asp-for="@Model.IdPedido" name="id">
    <div class="mt-3">
        @if (!Model.DataPedido.HasValue && Model.ItensPedido.Count() > 0)
        {
            <a asp-action="Index" asp-route-cid="@Model.IdCliente" class="btn btn-success">Não</a>
            <button class="btn btn-danger" type="submit">Sim</button>
        }
        else
        {
            <a asp-action="Index" asp-route-cid="@Model.IdCliente" class="btn btn-outline-success">Voltar</a>
        }
    </div>
</form>

WebEstoque/Views/Pedido/Index.cshtml
@model IEnumerable<Pedido>

@{
    ViewData["Title"] = "Order Page";
    var cliente = ViewBag.Cliente as Cliente;
    ViewBag.Subtitulo = $"Pedidos do Cliente <b>{cliente.Nome}</b>";
}


<header class="d-flex justify-content-between align-items-center">
    <div>
        <h1 class="text-primary">@Html.Raw(ViewBag.Subtitulo)</h1>
    </div>
    <div>
        <a asp-action="Cadastrar" asp-route-cid="@cliente.IdUsuario" class="btn btn-primary">Novo Pedido</a>
    </div>
</header>
<hr>


<partial name="~/views/shared/partialview/_Mensagem.cshtml" />

@if (Model.Count() > 0)
{
    <table class="table table-striped tabela-pedidos">
        <thead>
            <tr>
                <th>Número</th>
                <th>Data/Hora Pedido</th>
                <th>Valor Total</th>
                <th>Data/Hora Entrega</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pedido in Model)
            {
                <tr>
                    <td>@pedido.IdPedido.ToString("D4")</td>
                    <td>@(pedido.DataPedido.HasValue ? pedido.DataPedido : "Em Aberto")</td>
                    <td>@pedido.ValorTotal.Value.ToString("C")</td>
                    <td>@(pedido.DataEntrega.HasValue ? pedido.DataEntrega : "Não Entregue")</td>
                    <td>
                        @if (pedido.DataPedido.HasValue)
                        {
                            <span class="btn btn-sm btn-light"><i class="bi-check-lg text-gray" title="Pedido já fechado"></i></span>
                            @if (pedido.DataEntrega.HasValue)
                            {
                                <span class="btn btn-sm btn-light"><i class="bi-truck text-gray" title="Pedido já entregue"></i></span>
                            }
                            else
                            {
                                <a asp-action="Entregar" asp-route-id="@pedido.IdPedido" class="btn btn-sm btn-warning"><i class="bi-truck" title="Registrar entrega do pedido"></i></a>
                            }
                        }
                        else
                        {
                            <a asp-action="Fechar" asp-route-id="@pedido.IdPedido" class="btn btn-sm btn-success"><i class="bi-check-lg" title="Fechar pedido"></i></a>
                            <span class="btn btn-sm btn-light"><i class="bi-truck text-gray" title="Feche o pedido antes de registrar a entrega"></i></span>
                        }
                        <a asp-action="Index" asp-controller="ItemPedido" asp-route-ped="@pedido.IdPedido" class="btn btn-sm btn-info"><i class="bi-list-check" title="Itens do pedido"></i></a>                        
                        <a asp-action="Excluir" asp-route-id="@pedido.IdPedido" class="btn btn-sm btn-danger"><i class="bi-trash" title="Excluir pedido"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Não há nenhum pedido cadastrado para este cliente.</p>
}